blank_issues_enabled: false
contact_links:
  - name: 💬 Get Help & Ask Questions
    url: https://github.com/BleckWolf25/Evara-UI/discussions/new?category=general
    about: |
      Need assistance or unsure if something is a bug?
      Open a thread in our **Discussion forums** to ask questions, share ideas, or get support from the community.
